export enum HeroName {
	DVA = "D.Va",
	DOOMFIST = "Doomfist",
	JUNKER_QUEEN = "Junker Queen",
	MAUGA = "Mauga",
	ORISA = "Orisa",
	RAMATTRA = "Ramattra",
	REINHARDT = "Reinhardt",
	ROADHOG = "Roadhog",
	SIGMA = "Sigma",
	WINSTON = "Winston",
	WRECKING_BALL = "Wrecking Ball",
	ZARYA = "Zarya",

	ASHE = "Ashe",
	BASTION = "Bastion",
	CASSIDY = "Cassidy",
	ECHO = "Echo",
	GENJI = "Genji",
	HANZO = "Hanzo",
	JUNKRAT = "Junkrat",
	MEI = "Mei",
	PHARAH = "Pharah",
	REAPER = "Reaper",
	SOJOURN = "Sojourn",
	SOLDIER_76 = "Soldier: 76",
	SOMBRA = "Sombra",
	SYMMETRA = "Symmetra",
	TORBJORN = "Torbjörn",
	TRACER = "Tracer",
	WIDOWMAKER = "Widowmaker",

	ANA = "Ana",
	BAPTISTE = "Baptiste",
	BRIGITTE = "Brigitte",
	ILLARI = "Illari",
	KIRIKO = "Kiriko",
	LIFEWEAVER = "Lifeweaver",
	LUCIO = "Lúcio",
	MERCY = "Mercy",
	MOIRA = "Moira",
	HAZARD = "Hazard",
	JUNO = "Juno",
	ZENYATTA = "Zenyatta"
}